### PR TITLE
Update downloads.rst

### PR DESCRIPTION
**Pull request by Simplicitee**
## Fixes
* Fixed broken link to latest core download

### CODE REVIEW

**Comment by v-h-gn** [comment]
> ## Fixes
> * Fixed broken link to latest core download

**Review by v-h-gn — CHANGES_REQUESTED** [review]
Rather than making the inline reference more lengthy by adding the Latest Into it, just remove the latest from the actual text or use substitution.

**Comment by Simplicitee** [comment]
That seems like a very unnecessary change

**Comment by v-h-gn** [comment]
> That seems like a very unnecessary change

Its not unecessary, you can use tags defined in other files by referencing them. If you make them lengthy then it becomes tedious to write them out in other places.

**Comment by Simplicitee** [comment]
It's an unnecessary change.

**Comment by v-h-gn** [comment]
> It's an unecessary change

Its not unecessary, we want to keep things simple, to the point, and following our contribution guidelines.

**Comment by Simplicitee** [comment]
Keep the broken link

**Pull request closed without merging**
